version: '3'

services:

  cypress:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: npm test
    volumes:
      - ./cypress/results:/cypress/results
      - ./cypress/screenshots:/cypress/screenshots
      - ./cypress/videos:/cypress/videos
      - ./cypress-visual-screenshots/comparison:/cypress-visual-screenshots/comparison
      - ./cypress-visual-screenshots/diff:/cypress-visual-screenshots/diff
