export default {
  tocMenuButton: '[data-test="header-hamburger"]',
  tocMenuClose: '[data-test="icon-close"]',
  tocRoot: '[data-test="toc"]',
  tocArticleBlock: '[data-test="app__article"]',
  tocArticleTitle: '[data-test="starting-page-title"],h1 > .article__header > .article__title',
  tocListItems: '[data-test="internal-link toc-item"],[data-test="toc-item"]',
  tocListItem: (name) => `[data-test="internal-link toc-item"]:contains(${name}),
    [data-test="toc-item"]:contains(${name}),
    [data-test="internal-link toc-item--selected"]:contains(${name}),
    [data-test="toc-item--selected"]:contains(${name})`,
  tocItemArrow: (name) => `[data-test="internal-link toc-item"]:contains(${name}) > svg,
    [data-test="toc-item"]:contains(${name}) > svg,
    [data-test="internal-link toc-item--selected"]:contains(${name}) > svg,
    [data-test="toc-item--selected"]:contains(${name}) > svg`,
  cookiesBanner: '.jetbrains-cookies-banner__body',
  cookiesBannerClose: '.jetbrains-cookies-close-button',
};
