name: Test
on: workflow_dispatch
jobs:
  cypress-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          headless: true
          config: baseUrl=https://www.jetbrains.com/help/idea/
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: screenshots
          path: |
            cypress/screenshots/
            cypress/cypress-visual-screenshots/comparison
            cypress/cypress-visual-screenshots/diff
